"""empty message

Revision ID: 605fade9a3eb
Revises: c2863e5be32c
Create Date: 2018-12-26 13:35:13.410988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605fade9a3eb'
down_revision = 'c2863e5be32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_user_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('games_user_id_fkey', 'games', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
