"""empty message

Revision ID: 722a80b6cfe5
Revises: 5aefdb4264bc
Create Date: 2018-12-26 13:29:49.205264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722a80b6cfe5'
down_revision = '5aefdb4264bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamename', sa.String(length=20), nullable=False),
    sa.Column('scorePerPoint', sa.Integer(), nullable=False),
    sa.Column('timerChecked', sa.Boolean(), nullable=True),
    sa.Column('timerMinPerRound', sa.Integer(), nullable=True),
    sa.Column('timerMinPerGame', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gamename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
