"""empty message

Revision ID: c2863e5be32c
Revises: 6c96b3f75dd6
Create Date: 2018-12-26 13:33:37.315481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2863e5be32c'
down_revision = '6c96b3f75dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('gameName', sa.String(length=20), nullable=False))
    op.drop_constraint('games_gamename_key', 'games', type_='unique')
    op.create_unique_constraint(None, 'games', ['gameName'])
    op.drop_column('games', 'gamename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('gamename', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='unique')
    op.create_unique_constraint('games_gamename_key', 'games', ['gamename'])
    op.drop_column('games', 'gameName')
    # ### end Alembic commands ###
